---
- name: stop apache
  service: name=apache2 state=stopped

- name: Install python depends
  pip: virtualenv="/usr/local/share/letsencrypt/env" virtualenv_site_packages=no name={{ item }} state=latest
  with_items:
     - setuptools
     - pip
- name: More python depends
  pip: virtualenv="/usr/local/share/letsencrypt/env" virtualenv_site_packages=no name=letsencrypt
- name: Generate let's encrypt certificate
# The parameter standalone-supported-challenges has been changed with preferred-challanges
  shell: |
         /usr/local/share/letsencrypt/env/bin/letsencrypt certonly --standalone --agree-tos --email root@{{ mail_domain }} -d {{ mail_domain }} --preferred-challenges tls-sni-01,http
- name: Copy crt to apache
  file:
      src={{ item.src }}
      dest={{ item.dest }}
      state=link
  with_items:
      - {src: "/etc/letsencrypt/live/{{ mail_domain }}/privkey.pem", dest: "/etc/ssl/private/mailserver.pem" }
      - {src: "/etc/letsencrypt/live/{{ mail_domain }}/fullchain.pem", dest: "/etc/ssl/certs/mailserver.pem" }

- name: Cron renew crt
  cron:
       name="renew crt"
       special_time=monthly
       job="/root/renew_cert.sh"


